home_test:
    resource: "@HomeTestBundle/Controller/"
    type:     annotation
    prefix:   /
#########################################
user_index:
    path:     /
    defaults: { _controller: "HomeTestBundle:Cluster:index" }
#########################################

#home_test:
#    resource: "@HomeTestBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
